# coding: utf-8

"""
    otari-gateway

    A clean FastAPI gateway for otari with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from otari_control_plane.api.budgets_api import BudgetsApi


class TestBudgetsApi(unittest.TestCase):
    """BudgetsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BudgetsApi()

    def tearDown(self) -> None:
        pass

    def test_create_budget_v1_budgets_post(self) -> None:
        """Test case for create_budget_v1_budgets_post

        Create Budget
        """
        pass

    def test_delete_budget_v1_budgets_budget_id_delete(self) -> None:
        """Test case for delete_budget_v1_budgets_budget_id_delete

        Delete Budget
        """
        pass

    def test_get_budget_v1_budgets_budget_id_get(self) -> None:
        """Test case for get_budget_v1_budgets_budget_id_get

        Get Budget
        """
        pass

    def test_list_budgets_v1_budgets_get(self) -> None:
        """Test case for list_budgets_v1_budgets_get

        List Budgets
        """
        pass

    def test_update_budget_v1_budgets_budget_id_patch(self) -> None:
        """Test case for update_budget_v1_budgets_budget_id_patch

        Update Budget
        """
        pass


if __name__ == '__main__':
    unittest.main()
