# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class AgentTelemetrySeriesPoint(BaseModel):
    """
    One UTC time bucket of outcomes, behavior, and the spend beside them.  A cumulative series' increment is attributed to the bucket of the later point of each consecutive pair, so a bucket reports the growth observed inside it.
    """ # noqa: E501
    active_time: Optional[Union[StrictFloat, StrictInt]] = 0.0
    api_errors: Optional[StrictInt] = 0
    bucket_start: StrictStr
    commits: Optional[Union[StrictFloat, StrictInt]] = 0.0
    cost: Optional[Union[StrictFloat, StrictInt]] = 0.0
    lines_of_code: Optional[Union[StrictFloat, StrictInt]] = 0.0
    pull_requests: Optional[Union[StrictFloat, StrictInt]] = 0.0
    tool_calls: Optional[StrictInt] = 0
    turns: Optional[StrictInt] = 0
    __properties: ClassVar[List[str]] = ["active_time", "api_errors", "bucket_start", "commits", "cost", "lines_of_code", "pull_requests", "tool_calls", "turns"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AgentTelemetrySeriesPoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AgentTelemetrySeriesPoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active_time": obj.get("active_time") if obj.get("active_time") is not None else 0.0,
            "api_errors": obj.get("api_errors") if obj.get("api_errors") is not None else 0,
            "bucket_start": obj.get("bucket_start"),
            "commits": obj.get("commits") if obj.get("commits") is not None else 0.0,
            "cost": obj.get("cost") if obj.get("cost") is not None else 0.0,
            "lines_of_code": obj.get("lines_of_code") if obj.get("lines_of_code") is not None else 0.0,
            "pull_requests": obj.get("pull_requests") if obj.get("pull_requests") is not None else 0.0,
            "tool_calls": obj.get("tool_calls") if obj.get("tool_calls") is not None else 0,
            "turns": obj.get("turns") if obj.get("turns") is not None else 0
        })
        return _obj


