# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateKeyRequest(BaseModel):
    """
    Request model for creating a new API key.
    """ # noqa: E501
    allowed_models: Optional[List[StrictStr]] = Field(default=None, description="Model allow-list: null = any model, [] = deny all, or canonical instance:model entries (with instance:* / instance:prefix* wildcards).")
    capture_agent_telemetry: Optional[StrictBool] = Field(default=None, description="Per-key override of the deployment-wide capture_agent_telemetry setting: null (default) inherits it, true always stores this key's coding-agent telemetry, false always discards it. Covers both behavioral events (tool_result, tool_decision, user_prompt, api_error) from POST /v1/logs and outcome-metric data points (lines of code, commits, pull requests, active time) from POST /v1/metrics. Usage capture and billing are unaffected either way.")
    exclude_from_budget: Optional[StrictBool] = Field(default=False, description="When true, requests on this key are logged with cost but never reserved, reconciled into the user's spend, or gated by budget.")
    expires_at: Optional[datetime] = Field(default=None, description="Optional expiration timestamp")
    key_name: Optional[StrictStr] = Field(default=None, description="Optional name for the key")
    metadata: Optional[Dict[str, Any]] = Field(default=None, description="Optional metadata")
    reject_user_mismatch: Optional[StrictBool] = Field(default=None, description="Per-key override of the deployment-wide reject_user_mismatch setting: null (default) inherits it, true always rejects a request naming a different 'user', false always accepts it. Spend binds to this key's own user either way.")
    user_id: Optional[StrictStr] = Field(default=None, description="Optional user ID to associate with this key")
    __properties: ClassVar[List[str]] = ["allowed_models", "capture_agent_telemetry", "exclude_from_budget", "expires_at", "key_name", "metadata", "reject_user_mismatch", "user_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateKeyRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed_models (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_models is None and "allowed_models" in self.model_fields_set:
            _dict['allowed_models'] = None

        # set to None if capture_agent_telemetry (nullable) is None
        # and model_fields_set contains the field
        if self.capture_agent_telemetry is None and "capture_agent_telemetry" in self.model_fields_set:
            _dict['capture_agent_telemetry'] = None

        # set to None if expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.expires_at is None and "expires_at" in self.model_fields_set:
            _dict['expires_at'] = None

        # set to None if key_name (nullable) is None
        # and model_fields_set contains the field
        if self.key_name is None and "key_name" in self.model_fields_set:
            _dict['key_name'] = None

        # set to None if reject_user_mismatch (nullable) is None
        # and model_fields_set contains the field
        if self.reject_user_mismatch is None and "reject_user_mismatch" in self.model_fields_set:
            _dict['reject_user_mismatch'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateKeyRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_models": obj.get("allowed_models"),
            "capture_agent_telemetry": obj.get("capture_agent_telemetry"),
            "exclude_from_budget": obj.get("exclude_from_budget") if obj.get("exclude_from_budget") is not None else False,
            "expires_at": obj.get("expires_at"),
            "key_name": obj.get("key_name"),
            "metadata": obj.get("metadata"),
            "reject_user_mismatch": obj.get("reject_user_mismatch"),
            "user_id": obj.get("user_id")
        })
        return _obj


