# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from otari._client.models.deployment_user_organization_public import DeploymentUserOrganizationPublic
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DeploymentUserPublic(BaseModel):
    """
    An identity on this deployment, whatever organization it belongs to.  Not ``ActiveOrganizationMemberPublic``: that shape is a *membership* joined to an identity, scoped to one organization and hiding the suspended rows. This one is the identity itself, and its ``organizations`` list carries every membership at whatever status, because an account whose only membership is suspended is precisely what an operator comes here to find.  ``is_bootstrap_operator`` and ``is_self`` are the two rows an operator may not deactivate or demote, and they travel on the row so the page can disable those controls rather than offering ones the server refuses. Neither is an authorization: the server refuses either way. ``is_self`` is answered here because nothing else the dashboard fetches names the caller's identity, so without it the page could not tell which row is the reader's own.
    """ # noqa: E501
    created_at: datetime
    email: Optional[StrictStr]
    full_name: Optional[StrictStr]
    id: UUID
    is_active: StrictBool
    is_bootstrap_operator: StrictBool
    is_self: StrictBool
    is_superuser: StrictBool
    last_sign_in_at: Optional[datetime]
    organizations: List[DeploymentUserOrganizationPublic]
    __properties: ClassVar[List[str]] = ["created_at", "email", "full_name", "id", "is_active", "is_bootstrap_operator", "is_self", "is_superuser", "last_sign_in_at", "organizations"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeploymentUserPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in organizations (list)
        _items = []
        if self.organizations:
            for _item_organizations in self.organizations:
                if _item_organizations:
                    _items.append(_item_organizations.to_dict())
            _dict['organizations'] = _items
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if full_name (nullable) is None
        # and model_fields_set contains the field
        if self.full_name is None and "full_name" in self.model_fields_set:
            _dict['full_name'] = None

        # set to None if last_sign_in_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_sign_in_at is None and "last_sign_in_at" in self.model_fields_set:
            _dict['last_sign_in_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentUserPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "email": obj.get("email"),
            "full_name": obj.get("full_name"),
            "id": obj.get("id"),
            "is_active": obj.get("is_active"),
            "is_bootstrap_operator": obj.get("is_bootstrap_operator"),
            "is_self": obj.get("is_self"),
            "is_superuser": obj.get("is_superuser"),
            "last_sign_in_at": obj.get("last_sign_in_at"),
            "organizations": [DeploymentUserOrganizationPublic.from_dict(_item) for _item in obj["organizations"]] if obj.get("organizations") is not None else None
        })
        return _obj


