# coding: utf-8

"""
    otari-gateway

    A clean FastAPI gateway for otari with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class McpServerConfig(BaseModel):
    """
    Inline MCP server configuration accepted on the chat completions request.  Streamable HTTP transport. The `url` must be reachable from the gateway process.  URL safety is enforced at parse time:  * SSRF guard rejects private, link-local, and reserved IP ranges. Loopback is   allowed by default (sidecars, dev) — set ``GATEWAY_MCP_ALLOW_LOOPBACK=false`` to disable. * Plain ``http://`` is rejected when ``authorization_token`` is set, to keep   bearer tokens off the wire in cleartext.
    """ # noqa: E501
    allowed_tools: Optional[List[StrictStr]] = None
    authorization_token: Optional[StrictStr] = None
    name: Annotated[str, Field(min_length=1, strict=True, max_length=128)]
    purpose_hint: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = None
    url: Annotated[str, Field(min_length=1, strict=True)]
    __properties: ClassVar[List[str]] = ["allowed_tools", "authorization_token", "name", "purpose_hint", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of McpServerConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed_tools (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_tools is None and "allowed_tools" in self.model_fields_set:
            _dict['allowed_tools'] = None

        # set to None if authorization_token (nullable) is None
        # and model_fields_set contains the field
        if self.authorization_token is None and "authorization_token" in self.model_fields_set:
            _dict['authorization_token'] = None

        # set to None if purpose_hint (nullable) is None
        # and model_fields_set contains the field
        if self.purpose_hint is None and "purpose_hint" in self.model_fields_set:
            _dict['purpose_hint'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of McpServerConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_tools": obj.get("allowed_tools"),
            "authorization_token": obj.get("authorization_token"),
            "name": obj.get("name"),
            "purpose_hint": obj.get("purpose_hint"),
            "url": obj.get("url")
        })
        return _obj


