# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from otari._client.models.member_ceiling_public import MemberCeilingPublic
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MemberWorkspacePlacementPublic(BaseModel):
    """
    One workspace a member is in, with their role and ceiling there.  A ceiling is keyed on the *membership*, not on the person, so a member of two workspaces has two of them. The membership id is carried in its own right rather than read back off the ceiling, because it is needed precisely when there is no ceiling yet and one is about to be created.
    """ # noqa: E501
    ceiling: Optional[MemberCeilingPublic] = None
    role: StrictStr
    workspace_id: UUID
    workspace_member_id: UUID
    workspace_name: StrictStr
    __properties: ClassVar[List[str]] = ["ceiling", "role", "workspace_id", "workspace_member_id", "workspace_name"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MemberWorkspacePlacementPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of ceiling
        if self.ceiling:
            _dict['ceiling'] = self.ceiling.to_dict()
        # set to None if ceiling (nullable) is None
        # and model_fields_set contains the field
        if self.ceiling is None and "ceiling" in self.model_fields_set:
            _dict['ceiling'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MemberWorkspacePlacementPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ceiling": MemberCeilingPublic.from_dict(obj["ceiling"]) if obj.get("ceiling") is not None else None,
            "role": obj.get("role"),
            "workspace_id": obj.get("workspace_id"),
            "workspace_member_id": obj.get("workspace_member_id"),
            "workspace_name": obj.get("workspace_name")
        })
        return _obj


