# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from otari._client.models.content import Content
from otari._client.models.msg_audio import MSGAudio
from otari._client.models.msg_function_call import MSGFunctionCall
from otari._client.models.tool_calls_inner import ToolCallsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MSGChatCompletionAssistantMessageParam(BaseModel):
    """
    Messages sent by the model in response to user messages.
    """ # noqa: E501
    role: StrictStr
    audio: Optional[MSGAudio] = None
    content: Optional[Content] = None
    function_call: Optional[MSGFunctionCall] = None
    name: Optional[StrictStr] = None
    refusal: Optional[StrictStr] = None
    tool_calls: Optional[List[ToolCallsInner]] = None
    __properties: ClassVar[List[str]] = ["role", "audio", "content", "function_call", "name", "refusal", "tool_calls"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['assistant']):
            raise ValueError("must be one of enum values ('assistant')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MSGChatCompletionAssistantMessageParam from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of audio
        if self.audio:
            _dict['audio'] = self.audio.to_dict()
        # override the default output from pydantic by calling `to_dict()` of content
        if self.content:
            _dict['content'] = self.content.to_dict()
        # override the default output from pydantic by calling `to_dict()` of function_call
        if self.function_call:
            _dict['function_call'] = self.function_call.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tool_calls (list)
        _items = []
        if self.tool_calls:
            for _item_tool_calls in self.tool_calls:
                if _item_tool_calls:
                    _items.append(_item_tool_calls.to_dict())
            _dict['tool_calls'] = _items
        # set to None if audio (nullable) is None
        # and model_fields_set contains the field
        if self.audio is None and "audio" in self.model_fields_set:
            _dict['audio'] = None

        # set to None if content (nullable) is None
        # and model_fields_set contains the field
        if self.content is None and "content" in self.model_fields_set:
            _dict['content'] = None

        # set to None if function_call (nullable) is None
        # and model_fields_set contains the field
        if self.function_call is None and "function_call" in self.model_fields_set:
            _dict['function_call'] = None

        # set to None if refusal (nullable) is None
        # and model_fields_set contains the field
        if self.refusal is None and "refusal" in self.model_fields_set:
            _dict['refusal'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MSGChatCompletionAssistantMessageParam from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "role": obj.get("role"),
            "audio": MSGAudio.from_dict(obj["audio"]) if obj.get("audio") is not None else None,
            "content": Content.from_dict(obj["content"]) if obj.get("content") is not None else None,
            "function_call": MSGFunctionCall.from_dict(obj["function_call"]) if obj.get("function_call") is not None else None,
            "name": obj.get("name"),
            "refusal": obj.get("refusal"),
            "tool_calls": [ToolCallsInner.from_dict(_item) for _item in obj["tool_calls"]] if obj.get("tool_calls") is not None else None
        })
        return _obj


