# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class OAuthCallbackRequest(BaseModel):
    """
    The authorization code a provider handed the browser.  No ``redirect_uri``: this deployment derives its own from ``public_base_url`` so the URI used to build the authorization request and the one sent with the exchange are the same string by construction, and a browser cannot choose what this server sends to a provider.  ``state`` is required, and is what binds this callback to an authorization request this deployment actually made: it is claimed from ``oauth_pending_state`` before the code is sent anywhere, and the row it claims is what carries the PKCE verifier the exchange needs. The flow cookie ``/authorize`` set travels alongside and binds it to the browser.
    """ # noqa: E501
    code: Annotated[str, Field(strict=True, max_length=2048)] = Field(description="The authorization code from the provider's redirect.")
    state: Annotated[str, Field(strict=True, max_length=512)] = Field(description="The 'state' from the provider's redirect, as issued by /authorize.")
    __properties: ClassVar[List[str]] = ["code", "state"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OAuthCallbackRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OAuthCallbackRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "code": obj.get("code"),
            "state": obj.get("state")
        })
        return _obj


