# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ProviderEndpointPublic(BaseModel):
    """
    The API-facing shape. Never carries the key, only whether one is set.
    """ # noqa: E501
    api_base: StrictStr
    created_at: datetime
    default_params: Optional[Dict[str, Any]] = Field(default=None, description="Tags for cost attribution, recorded on the request's usage rows and filterable in the usage API: up to 16 string pairs, keys up to 64 characters and values up to 512. A null value is ignored. LiteLLM's nested `spend_logs_metadata` object is also read, and wins over a flat key of the same name; it is never forwarded to the provider.")
    id: UUID
    last4: Optional[StrictStr] = None
    name: StrictStr
    provider: StrictStr
    updated_at: Optional[datetime] = None
    user_id: Optional[StrictStr] = None
    workspace_id: UUID
    __properties: ClassVar[List[str]] = ["api_base", "created_at", "default_params", "id", "last4", "name", "provider", "updated_at", "user_id", "workspace_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ProviderEndpointPublic from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if default_params (nullable) is None
        # and model_fields_set contains the field
        if self.default_params is None and "default_params" in self.model_fields_set:
            _dict['default_params'] = None

        # set to None if last4 (nullable) is None
        # and model_fields_set contains the field
        if self.last4 is None and "last4" in self.model_fields_set:
            _dict['last4'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ProviderEndpointPublic from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_base": obj.get("api_base"),
            "created_at": obj.get("created_at"),
            "default_params": obj.get("default_params"),
            "id": obj.get("id"),
            "last4": obj.get("last4"),
            "name": obj.get("name"),
            "provider": obj.get("provider"),
            "updated_at": obj.get("updated_at"),
            "user_id": obj.get("user_id"),
            "workspace_id": obj.get("workspace_id")
        })
        return _obj


