# coding: utf-8

"""
    otari-gateway

    A clean FastAPI gateway for otari with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from otari._client.models.guardrail_config import GuardrailConfig
from otari._client.models.mcp_server_config import McpServerConfig
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ResponsesRequest(BaseModel):
    """
    OpenAI Responses API-compatible request.  Gateway-internal fields (``mcp_servers``, ``mcp_server_ids``, ``guardrails``, ``tools_header``, ``max_tool_iterations``) opt the request into gateway-managed MCP / sandbox / web_search / guardrails without changing the upstream wire shape. They're stripped before the request is forwarded.
    """ # noqa: E501
    guardrails: Optional[Annotated[List[GuardrailConfig], Field(max_length=8)]] = None
    input: Optional[Any]
    max_tool_iterations: Optional[Annotated[int, Field(le=25, strict=True, ge=1)]] = None
    mcp_server_ids: Optional[List[UUID]] = None
    mcp_servers: Optional[List[McpServerConfig]] = None
    model: StrictStr
    stream: Optional[StrictBool] = False
    tools: Optional[List[Dict[str, Any]]] = None
    tools_header: Optional[StrictStr] = None
    user: Optional[StrictStr] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["guardrails", "input", "max_tool_iterations", "mcp_server_ids", "mcp_servers", "model", "stream", "tools", "tools_header", "user"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ResponsesRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in guardrails (list)
        _items = []
        if self.guardrails:
            for _item_guardrails in self.guardrails:
                if _item_guardrails:
                    _items.append(_item_guardrails.to_dict())
            _dict['guardrails'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mcp_servers (list)
        _items = []
        if self.mcp_servers:
            for _item_mcp_servers in self.mcp_servers:
                if _item_mcp_servers:
                    _items.append(_item_mcp_servers.to_dict())
            _dict['mcp_servers'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if guardrails (nullable) is None
        # and model_fields_set contains the field
        if self.guardrails is None and "guardrails" in self.model_fields_set:
            _dict['guardrails'] = None

        # set to None if input (nullable) is None
        # and model_fields_set contains the field
        if self.input is None and "input" in self.model_fields_set:
            _dict['input'] = None

        # set to None if max_tool_iterations (nullable) is None
        # and model_fields_set contains the field
        if self.max_tool_iterations is None and "max_tool_iterations" in self.model_fields_set:
            _dict['max_tool_iterations'] = None

        # set to None if mcp_server_ids (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_server_ids is None and "mcp_server_ids" in self.model_fields_set:
            _dict['mcp_server_ids'] = None

        # set to None if mcp_servers (nullable) is None
        # and model_fields_set contains the field
        if self.mcp_servers is None and "mcp_servers" in self.model_fields_set:
            _dict['mcp_servers'] = None

        # set to None if tools (nullable) is None
        # and model_fields_set contains the field
        if self.tools is None and "tools" in self.model_fields_set:
            _dict['tools'] = None

        # set to None if tools_header (nullable) is None
        # and model_fields_set contains the field
        if self.tools_header is None and "tools_header" in self.model_fields_set:
            _dict['tools_header'] = None

        # set to None if user (nullable) is None
        # and model_fields_set contains the field
        if self.user is None and "user" in self.model_fields_set:
            _dict['user'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ResponsesRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "guardrails": [GuardrailConfig.from_dict(_item) for _item in obj["guardrails"]] if obj.get("guardrails") is not None else None,
            "input": obj.get("input"),
            "max_tool_iterations": obj.get("max_tool_iterations"),
            "mcp_server_ids": obj.get("mcp_server_ids"),
            "mcp_servers": [McpServerConfig.from_dict(_item) for _item in obj["mcp_servers"]] if obj.get("mcp_servers") is not None else None,
            "model": obj.get("model"),
            "stream": obj.get("stream") if obj.get("stream") is not None else False,
            "tools": obj.get("tools"),
            "tools_header": obj.get("tools_header"),
            "user": obj.get("user")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


