# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateStoredProviderRequest(BaseModel):
    """
    Update a stored provider. Omitted fields are unchanged; ``api_key`` rotates in place.
    """ # noqa: E501
    api_base: Optional[StrictStr] = None
    api_key: Optional[StrictStr] = Field(default=None, description="New API key. Omit to keep the existing one. Never returned.")
    client_args: Optional[Dict[str, Any]] = None
    expected_updated_at: Optional[StrictStr] = Field(default=None, description="Optimistic concurrency: if set, the update 412s unless it matches the stored updated_at.")
    provider_type: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["api_base", "api_key", "client_args", "expected_updated_at", "provider_type"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateStoredProviderRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if api_base (nullable) is None
        # and model_fields_set contains the field
        if self.api_base is None and "api_base" in self.model_fields_set:
            _dict['api_base'] = None

        # set to None if api_key (nullable) is None
        # and model_fields_set contains the field
        if self.api_key is None and "api_key" in self.model_fields_set:
            _dict['api_key'] = None

        # set to None if client_args (nullable) is None
        # and model_fields_set contains the field
        if self.client_args is None and "client_args" in self.model_fields_set:
            _dict['client_args'] = None

        # set to None if expected_updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.expected_updated_at is None and "expected_updated_at" in self.model_fields_set:
            _dict['expected_updated_at'] = None

        # set to None if provider_type (nullable) is None
        # and model_fields_set contains the field
        if self.provider_type is None and "provider_type" in self.model_fields_set:
            _dict['provider_type'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateStoredProviderRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_base": obj.get("api_base"),
            "api_key": obj.get("api_key"),
            "client_args": obj.get("client_args"),
            "expected_updated_at": obj.get("expected_updated_at"),
            "provider_type": obj.get("provider_type")
        })
        return _obj


