# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateSettingsRequest(BaseModel):
    """
    Change one or more runtime settings. Omitted fields are left unchanged.  Only the hot-changeable subset is accepted; startup-only fields are not settable over the API (they are display-only in the dashboard).
    """ # noqa: E501
    budget_estimate_default_output_tokens: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    default_pricing: Optional[StrictBool] = None
    file_understanding_enabled: Optional[StrictBool] = None
    model_cache_ttl_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    model_discovery: Optional[StrictBool] = None
    model_discovery_negative_ttl_seconds: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    model_discovery_timeout_seconds: Optional[Union[Annotated[float, Field(strict=True, gt=0.0)], Annotated[int, Field(strict=True, gt=0)]]] = None
    models_dev_cache_ttl_seconds: Optional[Annotated[int, Field(strict=True, ge=0)]] = None
    models_dev_metadata: Optional[StrictBool] = None
    reject_user_mismatch: Optional[StrictBool] = None
    require_pricing: Optional[StrictBool] = None
    stream_missing_usage_policy: Optional[StrictStr] = None
    vision_describe_max_tokens: Optional[Annotated[int, Field(strict=True, gt=0)]] = None
    vision_describe_model: Optional[StrictStr] = None
    vision_strategy: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["budget_estimate_default_output_tokens", "default_pricing", "file_understanding_enabled", "model_cache_ttl_seconds", "model_discovery", "model_discovery_negative_ttl_seconds", "model_discovery_timeout_seconds", "models_dev_cache_ttl_seconds", "models_dev_metadata", "reject_user_mismatch", "require_pricing", "stream_missing_usage_policy", "vision_describe_max_tokens", "vision_describe_model", "vision_strategy"]

    @field_validator('stream_missing_usage_policy')
    def stream_missing_usage_policy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['estimate', 'fail', 'allow_free']):
            raise ValueError("must be one of enum values ('estimate', 'fail', 'allow_free')")
        return value

    @field_validator('vision_strategy')
    def vision_strategy_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['describe', 'ocr', 'off']):
            raise ValueError("must be one of enum values ('describe', 'ocr', 'off')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateSettingsRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if budget_estimate_default_output_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.budget_estimate_default_output_tokens is None and "budget_estimate_default_output_tokens" in self.model_fields_set:
            _dict['budget_estimate_default_output_tokens'] = None

        # set to None if default_pricing (nullable) is None
        # and model_fields_set contains the field
        if self.default_pricing is None and "default_pricing" in self.model_fields_set:
            _dict['default_pricing'] = None

        # set to None if file_understanding_enabled (nullable) is None
        # and model_fields_set contains the field
        if self.file_understanding_enabled is None and "file_understanding_enabled" in self.model_fields_set:
            _dict['file_understanding_enabled'] = None

        # set to None if model_cache_ttl_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.model_cache_ttl_seconds is None and "model_cache_ttl_seconds" in self.model_fields_set:
            _dict['model_cache_ttl_seconds'] = None

        # set to None if model_discovery (nullable) is None
        # and model_fields_set contains the field
        if self.model_discovery is None and "model_discovery" in self.model_fields_set:
            _dict['model_discovery'] = None

        # set to None if model_discovery_negative_ttl_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.model_discovery_negative_ttl_seconds is None and "model_discovery_negative_ttl_seconds" in self.model_fields_set:
            _dict['model_discovery_negative_ttl_seconds'] = None

        # set to None if model_discovery_timeout_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.model_discovery_timeout_seconds is None and "model_discovery_timeout_seconds" in self.model_fields_set:
            _dict['model_discovery_timeout_seconds'] = None

        # set to None if models_dev_cache_ttl_seconds (nullable) is None
        # and model_fields_set contains the field
        if self.models_dev_cache_ttl_seconds is None and "models_dev_cache_ttl_seconds" in self.model_fields_set:
            _dict['models_dev_cache_ttl_seconds'] = None

        # set to None if models_dev_metadata (nullable) is None
        # and model_fields_set contains the field
        if self.models_dev_metadata is None and "models_dev_metadata" in self.model_fields_set:
            _dict['models_dev_metadata'] = None

        # set to None if reject_user_mismatch (nullable) is None
        # and model_fields_set contains the field
        if self.reject_user_mismatch is None and "reject_user_mismatch" in self.model_fields_set:
            _dict['reject_user_mismatch'] = None

        # set to None if require_pricing (nullable) is None
        # and model_fields_set contains the field
        if self.require_pricing is None and "require_pricing" in self.model_fields_set:
            _dict['require_pricing'] = None

        # set to None if stream_missing_usage_policy (nullable) is None
        # and model_fields_set contains the field
        if self.stream_missing_usage_policy is None and "stream_missing_usage_policy" in self.model_fields_set:
            _dict['stream_missing_usage_policy'] = None

        # set to None if vision_describe_max_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.vision_describe_max_tokens is None and "vision_describe_max_tokens" in self.model_fields_set:
            _dict['vision_describe_max_tokens'] = None

        # set to None if vision_describe_model (nullable) is None
        # and model_fields_set contains the field
        if self.vision_describe_model is None and "vision_describe_model" in self.model_fields_set:
            _dict['vision_describe_model'] = None

        # set to None if vision_strategy (nullable) is None
        # and model_fields_set contains the field
        if self.vision_strategy is None and "vision_strategy" in self.model_fields_set:
            _dict['vision_strategy'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateSettingsRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget_estimate_default_output_tokens": obj.get("budget_estimate_default_output_tokens"),
            "default_pricing": obj.get("default_pricing"),
            "file_understanding_enabled": obj.get("file_understanding_enabled"),
            "model_cache_ttl_seconds": obj.get("model_cache_ttl_seconds"),
            "model_discovery": obj.get("model_discovery"),
            "model_discovery_negative_ttl_seconds": obj.get("model_discovery_negative_ttl_seconds"),
            "model_discovery_timeout_seconds": obj.get("model_discovery_timeout_seconds"),
            "models_dev_cache_ttl_seconds": obj.get("models_dev_cache_ttl_seconds"),
            "models_dev_metadata": obj.get("models_dev_metadata"),
            "reject_user_mismatch": obj.get("reject_user_mismatch"),
            "require_pricing": obj.get("require_pricing"),
            "stream_missing_usage_policy": obj.get("stream_missing_usage_policy"),
            "vision_describe_max_tokens": obj.get("vision_describe_max_tokens"),
            "vision_describe_model": obj.get("vision_describe_model"),
            "vision_strategy": obj.get("vision_strategy")
        })
        return _obj


