# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from otari._client.models.usage_group_row import UsageGroupRow
from otari._client.models.usage_grouped_series_point import UsageGroupedSeriesPoint
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UsageGroupedSeries(BaseModel):
    """
    A per-group time series for the dashboard's stacked charts.  ``groups`` ranks the window's top groups by spend (plus the reconciling ``other`` fold), in the order a chart should stack and color them; ``points`` is sparse (only populated cells), keyed by canonical UTC ``bucket_start``.
    """ # noqa: E501
    bucket: StrictStr
    end_date: StrictStr
    group_by: StrictStr
    groups: List[UsageGroupRow]
    points: List[UsageGroupedSeriesPoint]
    start_date: StrictStr
    __properties: ClassVar[List[str]] = ["bucket", "end_date", "group_by", "groups", "points", "start_date"]

    @field_validator('bucket')
    def bucket_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['hour', 'day']):
            raise ValueError("must be one of enum values ('hour', 'day')")
        return value

    @field_validator('group_by')
    def group_by_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['model', 'user_id', 'api_key_id', 'source']):
            raise ValueError("must be one of enum values ('model', 'user_id', 'api_key_id', 'source')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageGroupedSeries from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in groups (list)
        _items = []
        if self.groups:
            for _item_groups in self.groups:
                if _item_groups:
                    _items.append(_item_groups.to_dict())
            _dict['groups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in points (list)
        _items = []
        if self.points:
            for _item_points in self.points:
                if _item_points:
                    _items.append(_item_points.to_dict())
            _dict['points'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageGroupedSeries from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bucket": obj.get("bucket"),
            "end_date": obj.get("end_date"),
            "group_by": obj.get("group_by"),
            "groups": [UsageGroupRow.from_dict(_item) for _item in obj["groups"]] if obj.get("groups") is not None else None,
            "points": [UsageGroupedSeriesPoint.from_dict(_item) for _item in obj["points"]] if obj.get("points") is not None else None,
            "start_date": obj.get("start_date")
        })
        return _obj


