# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from otari._client.models.api_key_id import ApiKeyId
from otari._client.models.model import Model
from otari._client.models.user_id import UserId
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UsageDeleteRequest(BaseModel):
    """
    Selection of imported usage rows to delete.
    """ # noqa: E501
    api_key_id: Optional[ApiKeyId] = None
    by_filter: Optional[StrictBool] = False
    end_date: Optional[datetime] = None
    endpoint: Optional[StrictStr] = None
    ids: Optional[Annotated[List[StrictStr], Field(max_length=1000)]] = None
    model: Optional[Model] = None
    priced: Optional[StrictBool] = None
    provider: Optional[StrictStr] = None
    source: Optional[StrictStr] = None
    source_label: Optional[StrictStr] = None
    start_date: Optional[datetime] = None
    status: Optional[StrictStr] = None
    tool: Optional[StrictStr] = None
    user_id: Optional[UserId] = None
    workspace_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["api_key_id", "by_filter", "end_date", "endpoint", "ids", "model", "priced", "provider", "source", "source_label", "start_date", "status", "tool", "user_id", "workspace_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UsageDeleteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of api_key_id
        if self.api_key_id:
            _dict['api_key_id'] = self.api_key_id.to_dict()
        # override the default output from pydantic by calling `to_dict()` of model
        if self.model:
            _dict['model'] = self.model.to_dict()
        # override the default output from pydantic by calling `to_dict()` of user_id
        if self.user_id:
            _dict['user_id'] = self.user_id.to_dict()
        # set to None if api_key_id (nullable) is None
        # and model_fields_set contains the field
        if self.api_key_id is None and "api_key_id" in self.model_fields_set:
            _dict['api_key_id'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        # set to None if endpoint (nullable) is None
        # and model_fields_set contains the field
        if self.endpoint is None and "endpoint" in self.model_fields_set:
            _dict['endpoint'] = None

        # set to None if ids (nullable) is None
        # and model_fields_set contains the field
        if self.ids is None and "ids" in self.model_fields_set:
            _dict['ids'] = None

        # set to None if model (nullable) is None
        # and model_fields_set contains the field
        if self.model is None and "model" in self.model_fields_set:
            _dict['model'] = None

        # set to None if priced (nullable) is None
        # and model_fields_set contains the field
        if self.priced is None and "priced" in self.model_fields_set:
            _dict['priced'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if source_label (nullable) is None
        # and model_fields_set contains the field
        if self.source_label is None and "source_label" in self.model_fields_set:
            _dict['source_label'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if tool (nullable) is None
        # and model_fields_set contains the field
        if self.tool is None and "tool" in self.model_fields_set:
            _dict['tool'] = None

        # set to None if user_id (nullable) is None
        # and model_fields_set contains the field
        if self.user_id is None and "user_id" in self.model_fields_set:
            _dict['user_id'] = None

        # set to None if workspace_id (nullable) is None
        # and model_fields_set contains the field
        if self.workspace_id is None and "workspace_id" in self.model_fields_set:
            _dict['workspace_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UsageDeleteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "api_key_id": ApiKeyId.from_dict(obj["api_key_id"]) if obj.get("api_key_id") is not None else None,
            "by_filter": obj.get("by_filter") if obj.get("by_filter") is not None else False,
            "end_date": obj.get("end_date"),
            "endpoint": obj.get("endpoint"),
            "ids": obj.get("ids"),
            "model": Model.from_dict(obj["model"]) if obj.get("model") is not None else None,
            "priced": obj.get("priced"),
            "provider": obj.get("provider"),
            "source": obj.get("source"),
            "source_label": obj.get("source_label"),
            "start_date": obj.get("start_date"),
            "status": obj.get("status"),
            "tool": obj.get("tool"),
            "user_id": UserId.from_dict(obj["user_id"]) if obj.get("user_id") is not None else None,
            "workspace_id": obj.get("workspace_id")
        })
        return _obj


