# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkspaceWebSearchConfigUpdate(BaseModel):
    """
    The configuration to store for a workspace, as a whole.  ``PUT`` semantics, ported from the hosted ``WorkspaceWebSearchConfigUpdate``: what is sent is what the workspace has afterwards, so an omitted field is cleared rather than left as it was.
    """ # noqa: E501
    allowed_domains: Optional[List[StrictStr]] = Field(default=None, description="Results are kept only from these domains; intersected with any list the request sends")
    blocked_domains: Optional[List[StrictStr]] = Field(default=None, description="Results from these domains are dropped; added to any list the request sends")
    enabled: StrictBool = Field(description="False refuses web search for this workspace, both the otari_web_search tool and POST /v1/search. The fields below narrow the tool only.")
    max_results: Optional[Annotated[int, Field(le=20, strict=True, gt=0)]] = Field(default=None, description="Ceiling on results one search returns; only ever lowers the effective limit, so at most 20")
    provider_options: Optional[Dict[str, Any]] = Field(default=None, description="Provider-native request fields used as defaults (e.g. exa's 'type', searxng's 'engines').")
    purpose_hint: Optional[Annotated[str, Field(strict=True, max_length=2048)]] = Field(default=None, description="Hint used when a request declares otari_web_search without one of its own")
    __properties: ClassVar[List[str]] = ["allowed_domains", "blocked_domains", "enabled", "max_results", "provider_options", "purpose_hint"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceWebSearchConfigUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed_domains (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_domains is None and "allowed_domains" in self.model_fields_set:
            _dict['allowed_domains'] = None

        # set to None if blocked_domains (nullable) is None
        # and model_fields_set contains the field
        if self.blocked_domains is None and "blocked_domains" in self.model_fields_set:
            _dict['blocked_domains'] = None

        # set to None if max_results (nullable) is None
        # and model_fields_set contains the field
        if self.max_results is None and "max_results" in self.model_fields_set:
            _dict['max_results'] = None

        # set to None if provider_options (nullable) is None
        # and model_fields_set contains the field
        if self.provider_options is None and "provider_options" in self.model_fields_set:
            _dict['provider_options'] = None

        # set to None if purpose_hint (nullable) is None
        # and model_fields_set contains the field
        if self.purpose_hint is None and "purpose_hint" in self.model_fields_set:
            _dict['purpose_hint'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceWebSearchConfigUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_domains": obj.get("allowed_domains"),
            "blocked_domains": obj.get("blocked_domains"),
            "enabled": obj.get("enabled"),
            "max_results": obj.get("max_results"),
            "provider_options": obj.get("provider_options"),
            "purpose_hint": obj.get("purpose_hint")
        })
        return _obj


