# coding: utf-8

"""
    otari

    Otari, an OpenAI-compatible LLM gateway with API key management

    The version of the OpenAPI document: 0.0.0-dev
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkspaceMcpServerCreate(BaseModel):
    """
    Request body for registering a server.  ``authorization_token`` is never stored as sent: it is encrypted with ``OTARI_SECRET_KEY`` and only the ciphertext is kept, the same convention `entities.ProviderCredential` and `OrgProviderKey` already use.
    """ # noqa: E501
    allowed_tools: Optional[Annotated[List[Annotated[str, Field(strict=True, max_length=256)]], Field(max_length=200)]] = Field(default=None, description="Allow-list of tool names; null exposes every tool the server offers")
    authorization_token: Optional[Annotated[str, Field(strict=True, max_length=8192)]] = Field(default=None, description="Bearer token for the server; requires an https URL. Encrypted at rest, never returned")
    enabled: Optional[StrictBool] = Field(default=True, description="Whether a request naming this server actually reaches it")
    name: Annotated[str, Field(min_length=1, strict=True, max_length=128)] = Field(description="Label for the server, unique within the workspace")
    purpose_hint: Optional[Annotated[str, Field(strict=True, max_length=2000)]] = Field(default=None, description="Hint prepended to the system message to help the model choose")
    url: Annotated[str, Field(min_length=1, strict=True, max_length=2048)] = Field(description="Streamable HTTP MCP endpoint")
    __properties: ClassVar[List[str]] = ["allowed_tools", "authorization_token", "enabled", "name", "purpose_hint", "url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkspaceMcpServerCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if allowed_tools (nullable) is None
        # and model_fields_set contains the field
        if self.allowed_tools is None and "allowed_tools" in self.model_fields_set:
            _dict['allowed_tools'] = None

        # set to None if authorization_token (nullable) is None
        # and model_fields_set contains the field
        if self.authorization_token is None and "authorization_token" in self.model_fields_set:
            _dict['authorization_token'] = None

        # set to None if purpose_hint (nullable) is None
        # and model_fields_set contains the field
        if self.purpose_hint is None and "purpose_hint" in self.model_fields_set:
            _dict['purpose_hint'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkspaceMcpServerCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "allowed_tools": obj.get("allowed_tools"),
            "authorization_token": obj.get("authorization_token"),
            "enabled": obj.get("enabled") if obj.get("enabled") is not None else True,
            "name": obj.get("name"),
            "purpose_hint": obj.get("purpose_hint"),
            "url": obj.get("url")
        })
        return _obj


